create database whatever  -- creating new database
\c whatever -- connecting other database


create role kamron with superuser login encrypted password 'password'; -- creating custom role for database
--there , we created role which named 'kamron' with password 'password'


--DDL
create table users (
  -- user_id int8 generated by default as identity primary key,
  user_id int8 generated always as identity primary key,

  username character varying(32) not null
);
comment on table users is 'Foydalanuvchilar';
--DML
insert into users(username) values("Bahtiyorov Kamron");
